CREATE DATABASE IF NOT EXISTS mysns
DEFAULT CHARACTER SET utf COLLATE utf8_general_ci;

USE mysns

CREATE TABLE IF NOT EXISTS user(
	id VARCHAR(64) PRIMARY KEY COMMENT "email",
	password VARCHAR(32),
	name VARCHAR(32),
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS feed(
	no INT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT "sequence",
	id VARCHAR(32) COMMENT "same as the table user",
	content VARCHAR(4096),
	ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);